services:
  python:
    build: ./work
    container_name: PYTHON
    tty: true
    stdin_open: true
    volumes:
      - ./work:/work
      - ./models:/root/.cache/huggingface/hub
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - '8000:8000'
    networks:
      - external

networks:
  external:
    external: true
